## Исключения
Исключение – это нежелательная ситуация, которая возникает во время выполнения программы и нарушает нормальный ход ее работы. Такая ситуация может возникнуть, например, при попытке чтения из несуществующего файла, делении на ноль, сбое устройства и так далее. Исключение можно перехватить, чтобы принять соответствующие меры.

## Операторы try, catch, finally, throw, throws: обработка исключений и примеры использования

Для перехвата исключительных ситуаций создается объект исключения, который передается среде выполнения. Он содержит информацию об ошибке, в том числе ее тип и состояние программы на момент возникновения ошибки. Создание объекта исключения и его передача среде выполнения называется выбрасыванием исключительной ситуации.

### try-catch

Для перехвата исключения используется конструкция **try**–**catch**. Код, который нужно проверить на исключение, заключается в блок try, а код, обрабатывающий исключение – в блок catch.

### finally

Блок **finally** выполняется после try-catch, независимо от того, возникло ли исключение. Это необязательный блок, но если нет блока catch, то блок finally необходим.

В этом блоке можно, например, закрыть файл, открытый в блоке try, как в приведенном ниже коде.

### throws

Ключевое слово **throws** используется, чтобы в сигнатуре метода указать, что он выбрасывает исключение. Его можно использовать, чтобы передавать исключения по стеку вызовов и указать, что эти исключения не обязательно должны обрабатываться в методе, в котором они объявлены.
## Иерархия исключений Java

Исключения в Java делятся на две основные категории: встроенные и пользовательские.

### Встроенные исключения

Встроенные исключения – это исключения, которые заранее определены в Java.

Когда возникает встроенное исключение, виртуальная машина Java (JVM) создает объект, принадлежащий классу встроенного исключения. Все исключения происходят от класса java.lang.Throwable, но они определены в нескольких пакетах.

![Исключения в Java — пояснение и примеры](https://highload.today/wp-content/uploads/2022/09/Hierarchy.jpg.webp)

Класс **Throwable** происходит непосредственно об класса Object и является корневым классом дерева классов исключений. От него происходят два подкласса: Error и Exception. Ошибки и исключения, которые встречаются в программах на Java, являются объектами этих классов.

С использованием класса Throwable можно создавать собственные исключения.

Класс **Error** является надклассом для всех классов ошибок времени выполнения. Он завершает выполнение программы, если происходит ошибка, связанная с системой или ресурсами (JVM).

Ошибки обычно представляют собой необычную проблему, после которой сложно произвести восстановление. Они происходят не по вине программиста, а из-за ненадлежащей работы системы или выделения ресурсов.

Примеры ошибок: AssertionError, LinkageError, OutOfMmeoryError, StackOverFlowError, VirtualMachineError.

Класс **Exception** представляет ошибки, вызванные программой или внешними факторами. Это надкласс для все классов исключений.

Для этого класса существует два конструктора:

-   public Exception() (по умолчанию)
-   public Exception(String message) (принимает строковое сообщение как аргумент)

Эти конструкторы наследуются всеми подклассами исключений. Сам по себе класс Exception не предоставляет собственных методов. Он наследует методы класса Throwable.

Встроенные исключения делятся на две группы: проверяемые (checked) и непроверяемые (unchecked).

### Проверяемые исключения в Java

Проверяемые исключения проверяются компилятором Java во время компиляции и _не_ являются подклассами RuntimeException (исключения времени выполнения).

Если метод выбрасывает проверяемое исключение, то это исключение необходимо обработать либо в этом же методе, либо передать вызывающему методу.

Проверяемые исключения обрабатываются либо в блоке try-catch, либо в объявлении метода с ключевым словом throws. Если исключение не обработано, происходит ошибка компиляции.

Проверяемыми исключениями являются все исключения, кроме RuntimeException, Error и их подклассов.

Примеры проверяемых исключений: ClassNotFoundException, IOException, SQLException, IllegalAccessException, FileNotFoundException.

### Непроверяемые исключения (исключения времени выполнения) в Java

Непроверяемые исключения в Java – это исключения, которые проверяются JVM, а не компилятором Java. Они возникают во время выполнения программы.

Все подклассы RuntimeException называются непроверяемыми исключениями или исключениями времени выполнения в Java.

Можно написать программу на Java и скомпилировать ее, но мы не увидим непроверяемых исключений и ошибок, пока не запустим эту программу.

Компилятор Java не проверяет исключения времени выполнения во время компиляции, независимо от того, обрабатывает ли их программа.

Если в методе возникает исключение времени выполнения, а программист не обрабатывает его, JVM прекращает выполнение программы, не выполняя остаток кода.

Примеры непроверяемых исключений: ArithmeticException, ArrayIndexOutOfBoundsException, ClassCastException, NegativeArraySizeException, NullPointerException.

## Пользовательские исключения

Пользовательские исключения создаются пользователями или программистами в соответствии с их собственными потребностями. Они создаются путем расширения класса Exception.

Примером пользовательского исключения может служить исключение, выбрасываемое, если пользователь пытается открыть банковский счет, но не достиг возраста 18 лет. В таком случае может быть выдано сообщение о том, что требуется открыть счет с кем-то из родителей. 

Чтобы использовать пользовательское исключение, нужно выполнить следующие действия.

-   Определить класс, расширяющий класс Exception.
-   Определить конструктор. Если не требуется хранить сведения об исключении, определяется конструктор по умолчанию. Если требуется сохранить сведения об исключении в виде строки, определяется конструктор с параметром.
-   Создать объект пользовательского исключения и выбросить его с помощью ключевого слова throw.

## Try-With-Resources
Начиная с седьмой версии Java предлагает улучшенное управление ресурсами, которые должны быть закрыты после окончания работы с ними. К таким ресурсам относятся, например, файлы потоки, соединения с базами данных и сокетами. Этой цели служит специальная языковая конструкция try-with-resources. Для того чтобы это автоматическое закрытие работало создан специальный интерфейс `AutoCloseable`.
